import { useState } from 'react'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import Layout from '../components/Layout.js'
import React, { useRef } from 'react';

export default function updateArticle() {
  
  const supabase = useSupabaseClient()
  const [message, setMessage] = useState(null)
  const [value, setValue] = React.useState('simple text');

  function onChange(e) {
    setValue(e.target.value);
  }

  const onSubmit = async function(e){
    e.preventDefault()

    const data = new FormData(e.target)
    const { error } = await supabase
      .from('articles')
      .update(Object.fromEntries(data), { returning: 'minimal' })
      .eq('id',id)

    
    if(error){
      setMessage('Sorry, an unexpected error occured.')
    }else{
      setMessage(
        <div>
          <h2 className="text-center mt-3">Confirmation</h2>
          <p>Your article has been updating.</p>
        </div>
      )
    }
  }
  
  return (
    <Layout>
      <Head>
        <title>WebTech - contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='wt-title'>
        Article format
      </h1>
      
      <form className="[&_span]:block grid gap-3" onSubmit={onSubmit}>
      <div className="mb-5">
        <label
          for="title"
          className="mb-3 block text-base font-medium text-[#07074D]"
        >
          Title
        </label>
        <input
          type="text"
          name="title"
          placeholder="Title"
          className="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
        />
      </div>
      <div className="mb-5">
        <label
          for="Slug"
          className="mb-3 block text-base font-medium text-[#07074D]"
        >
          Slug
        </label>
        <input
          type="text"
          name="slug"
          placeholder="Pick a slug for your article"
          className="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
        />
      </div>
      <div className="mb-5">
        <label
          for="type"
          className="mb-3 block text-base font-medium text-[#07074D]"
        >
          Type
        </label>
        <input
          type="text"
          name="type"
          placeholder="Describe your content"
          className="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
        />
      </div>
      <div className="mb-5">
        <label
          for="content"
          className="mb-3 block text-base font-medium text-[#07074D]"
        >
          Content
        </label>
        <textarea
          rows="4"
          name="content"
          placeholder="Type your message"
          className="w-full resize-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
        ></textarea>
      </div>
      <div>
        <button
          className="hover:shadow-form rounded-md bg-[#6A64F1] py-3 px-8 text-base font-semibold text-white outline-none"
        >
          Update 
        </button>
      </div>
    </form>
      {message &&
        <div
          aria-label="Overlow below the drawer dialog"
          className="fixed inset-0 bg-black/80 flex items-center justify-center"
          onClick={() => setMessage(null)}
          role="dialog"
        >
          <div
            aria-label="Alert pane"
            className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
          >
            {message}
          </div>
        </div>
      }
    </Layout>
  )
}
